"""One-time Stripe setup for a fresh account.

Reads STRIPE_SECRET_KEY from the environment (backend/.env.local is loaded by
app.config from the repo-root .env.local). Creates the TimeIQ product and yearly prices, registers the
webhook endpoint, configures the customer portal, and appends the resulting
ids and the webhook signing secret to the repo-root .env.local. Secrets are written
to the file, never printed.

Usage (from backend/):
    .venv/bin/python scripts/stripe_setup.py [--backend-url https://api.example.com]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import stripe  # noqa: E402

from app.config import settings  # noqa: E402

ENV_PATH = Path(__file__).resolve().parent.parent.parent / ".env.local"  # repo root, same file app.config loads
WEBHOOK_EVENTS = [
    "checkout.session.completed",
    "customer.subscription.created",
    "customer.subscription.updated",
    "customer.subscription.deleted",
    "invoice.paid",
    "invoice.payment_failed",
]


def upsert_env(values: dict[str, str]) -> None:
    lines = ENV_PATH.read_text().splitlines() if ENV_PATH.exists() else []
    keys = set(values)
    out = []
    for line in lines:
        name = line.split("=", 1)[0].strip()
        if name in keys:
            continue
        out.append(line)
    if out and out[-1].strip():
        out.append("")
    out.append("# Stripe (generated by scripts/stripe_setup.py)")
    out += [f"{k}={v}" for k, v in values.items()]
    ENV_PATH.write_text("\n".join(out) + "\n")


def find_or_create_product() -> stripe.Product:
    for p in stripe.Product.list(active=True, limit=100).auto_paging_iter():
        if p.name == "TimeIQ":
            return p
    return stripe.Product.create(
        name="TimeIQ",
        description="Scheduling, time tracking, and invoicing in one calm workspace.",
    )


def find_or_create_price(product_id: str, cents: int, nickname: str) -> stripe.Price:
    for pr in stripe.Price.list(product=product_id, active=True, limit=100).auto_paging_iter():
        if pr.unit_amount == cents and pr.recurring and pr.recurring.interval == "year":
            return pr
    return stripe.Price.create(
        product=product_id,
        unit_amount=cents,
        currency="usd",
        recurring={"interval": "year"},
        nickname=nickname,
    )


def find_or_create_webhook(url: str) -> stripe.WebhookEndpoint:
    for ep in stripe.WebhookEndpoint.list(limit=100).auto_paging_iter():
        if ep.url == url:
            return ep
    return stripe.WebhookEndpoint.create(url=url, enabled_events=WEBHOOK_EVENTS, description="TimeIQ backend")


def ensure_portal(return_url: str) -> None:
    configs = stripe.billing_portal.Configuration.list(limit=10)
    if any(c.is_default for c in configs.data):
        return
    stripe.billing_portal.Configuration.create(
        business_profile={"headline": "TimeIQ billing"},
        default_return_url=return_url,
        features={
            "customer_update": {"enabled": True, "allowed_updates": ["email", "address"]},
            "invoice_history": {"enabled": True},
            "payment_method_update": {"enabled": True},
            "subscription_cancel": {"enabled": True, "mode": "at_period_end"},
        },
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--backend-url", default=settings.BACKEND_URL)
    ap.add_argument("--frontend-url", default=settings.FRONTEND_URL)
    args = ap.parse_args()

    if not settings.STRIPE_SECRET_KEY:
        sys.exit("STRIPE_SECRET_KEY is not set (add it to the repo-root .env.local)")
    stripe.api_key = settings.STRIPE_SECRET_KEY
    mode = "TEST" if settings.STRIPE_SECRET_KEY.startswith("sk_test") else "LIVE"

    product = find_or_create_product()
    founder = find_or_create_price(product.id, 500, "Founding member — $5/year")
    standard = find_or_create_price(product.id, 2900, "Standard — $29/year")

    webhook_url = f"{args.backend_url.rstrip('/')}/api/webhooks/stripe"
    endpoint = find_or_create_webhook(webhook_url)
    values = {
        "STRIPE_PRICE_FOUNDER": founder.id,
        "STRIPE_PRICE_STANDARD": standard.id,
        "FOUNDER_SEATS": "100",
    }
    # The signing secret is only returned at creation time.
    if getattr(endpoint, "secret", None):
        values["STRIPE_WEBHOOK_SECRET"] = endpoint.secret
        secret_note = "written to .env.local"
    else:
        secret_note = "endpoint already existed; copy its signing secret from the dashboard"

    ensure_portal(f"{args.frontend_url.rstrip('/')}/settings")
    upsert_env(values)

    print(f"Stripe {mode} mode setup complete")
    print(f"  product        {product.id}")
    print(f"  founder price  {founder.id}  $5/year")
    print(f"  standard price {standard.id}  $29/year")
    print(f"  webhook        {webhook_url}")
    print(f"  webhook secret {secret_note}")
    print(f"  env file       {ENV_PATH}")


if __name__ == "__main__":
    main()
